# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 04:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import positions.fields


class Migration(migrations.Migration):

    replaces = [('exhibits', '0001_initial'), ('exhibits', '0002_auto_20160301_0228'), ('exhibits', '0003_auto_20160301_2121'), ('exhibits', '0004_auto_20160301_2329'), ('exhibits', '0005_auto_20160301_2330'), ('exhibits', '0006_auto_20160301_2351'), ('exhibits', '0007_auto_20160302_2003'), ('exhibits', '0008_auto_20160302_2253'), ('exhibits', '0009_auto_20160302_2314'), ('exhibits', '0010_exhibit_hero'), ('exhibits', '0011_auto_20160310_0041'), ('exhibits', '0012_theme_hero'), ('exhibits', '0013_auto_20160314_2114'), ('exhibits', '0014_auto_20160314_2116'), ('exhibits', '0015_auto_20160316_1940'), ('exhibits', '0016_auto_20160316_2254'), ('exhibits', '0017_auto_20160317_2010'), ('exhibits', '0018_auto_20160406_0544'), ('exhibits', '0019_exhibititem_lesson_plan_order'), ('exhibits', '0020_exhibit_byline_render_as'), ('exhibits', '0021_auto_20160406_0801'), ('exhibits', '0022_exhibit_short_title'), ('exhibits', '0023_auto_20160406_1657'), ('exhibits', '0024_auto_20160406_2029'), ('exhibits', '0025_auto_20160406_2029'), ('exhibits', '0026_auto_20160406_2040'), ('exhibits', '0027_historicalessay_color'), ('exhibits', '0028_auto_20160406_2109'), ('exhibits', '0029_auto_20160406_2131'), ('exhibits', '0030_lessonplan_byline_render_as'), ('exhibits', '0031_auto_20160406_2318'), ('exhibits', '0032_auto_20160407_0111'), ('exhibits', '0033_auto_20160421_1705'), ('exhibits', '0034_auto_20160425_1703'), ('exhibits', '0035_auto_20160425_1706'), ('exhibits', '0036_auto_20160425_1820'), ('exhibits', '0037_auto_20160505_0037'), ('exhibits', '0038_auto_20160509_1930'), ('exhibits', '0038_auto_20160509_1923'), ('exhibits', '0039_merge'), ('exhibits', '0040_theme_category'), ('exhibits', '0041_auto_20160517_2326'), ('exhibits', '0042_auto_20160520_2338'), ('exhibits', '0043_auto_20160606_1656'), ('exhibits', '0044_auto_20160606_1716')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ExhibitItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=200)),
                ('exhibit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibits.Exhibit')),
                ('essay', models.TextField(blank=True, verbose_name='Item-level exhibit information')),
                ('order', positions.fields.PositionField(default=-1)),
                ('render_as', models.CharField(choices=[('H', 'HTML'), ('T', 'Plain Text'), ('M', 'Markdown')], default='T', max_length=1)),
                ('exact', models.BooleanField(default=False)),
                ('lat', models.FloatField(default=37.8086906)),
                ('lon', models.FloatField(default=-122.2675416)),
                ('place', models.CharField(blank=True, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalEssay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('blockquote', models.CharField(blank=True, max_length=200)),
                ('about_essay', models.TextField(blank=True)),
                ('essay', models.TextField(blank=True)),
                ('render_as', models.CharField(choices=[('H', 'HTML'), ('T', 'Plain Text'), ('M', 'Markdown')], default='H', max_length=1)),
                ('go_further', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('essay', models.TextField(blank=True, verbose_name='Lesson plan')),
                ('render_as', models.CharField(choices=[('H', 'HTML'), ('T', 'Plain Text'), ('M', 'Markdown')], default='H', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='NotesItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', positions.fields.PositionField(default=-1)),
                ('essay', models.TextField(blank=True)),
                ('render_as', models.CharField(choices=[('H', 'HTML'), ('T', 'Plain Text'), ('M', 'Markdown')], default='H', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('color', models.CharField(blank=True, max_length=20)),
                ('about_theme', models.TextField(blank=True)),
                ('essay', models.TextField(blank=True, verbose_name='Theme overview')),
                ('render_as', models.CharField(choices=[('H', 'HTML'), ('T', 'Plain Text'), ('M', 'Markdown')], default='H', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='exhibit',
            name='byline',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='blockquote',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='overview',
            field=models.TextField(blank=True, verbose_name='Exhibit Overview'),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='render_as',
            field=models.CharField(choices=[('H', 'HTML'), ('T', 'Plain Text'), ('M', 'Markdown')], default='H', max_length=1),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='notesitem',
            name='exhibit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibits.Exhibit'),
        ),
        migrations.CreateModel(
            name='HistoricalEssayExhibit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', positions.fields.PositionField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlanExhibit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', positions.fields.PositionField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='ThemeExhibit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', positions.fields.PositionField(default=-1)),
            ],
        ),
        migrations.AddField(
            model_name='exhibit',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='Ready for publication?'),
        ),
        migrations.AlterField(
            model_name='notesitem',
            name='essay',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='notesitem',
            name='render_as',
            field=models.CharField(choices=[('H', 'HTML'), ('T', 'Plain Text'), ('M', 'Markdown')], default='T', max_length=1),
        ),
        migrations.AddField(
            model_name='themeexhibit',
            name='exhibit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibits.Exhibit'),
        ),
        migrations.AddField(
            model_name='themeexhibit',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibits.Theme'),
        ),
        migrations.AddField(
            model_name='lessonplanexhibit',
            name='exhibit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibits.Exhibit'),
        ),
        migrations.AddField(
            model_name='lessonplanexhibit',
            name='lessonPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibits.LessonPlan'),
        ),
        migrations.AddField(
            model_name='historicalessayexhibit',
            name='exhibit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibits.Exhibit'),
        ),
        migrations.AddField(
            model_name='historicalessayexhibit',
            name='historicalEssay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibits.HistoricalEssay'),
        ),
        migrations.RenameField(
            model_name='themeexhibit',
            old_name='position',
            new_name='order',
        ),
        migrations.AlterUniqueTogether(
            name='themeexhibit',
            unique_together=set([('exhibit', 'theme')]),
        ),
        migrations.RenameField(
            model_name='lessonplanexhibit',
            old_name='position',
            new_name='order',
        ),
        migrations.AlterUniqueTogether(
            name='lessonplanexhibit',
            unique_together=set([('exhibit', 'lessonPlan')]),
        ),
        migrations.RenameField(
            model_name='historicalessayexhibit',
            old_name='position',
            new_name='order',
        ),
        migrations.AlterUniqueTogether(
            name='historicalessayexhibit',
            unique_together=set([('exhibit', 'historicalEssay')]),
        ),
        migrations.RenameModel(
            old_name='ThemeExhibit',
            new_name='ExhibitTheme',
        ),
        migrations.CreateModel(
            name='HistoricalEssayTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', positions.fields.PositionField(default=-1)),
                ('historicalEssay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibits.HistoricalEssay')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibits.Theme')),
            ],
            options={
                'verbose_name': 'Historical Essay',
            },
        ),
        migrations.CreateModel(
            name='LessonPlanTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', positions.fields.PositionField(default=-1)),
                ('lessonPlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibits.LessonPlan')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibits.Theme')),
            ],
            options={
                'verbose_name': 'Lesson Plan',
            },
        ),
        migrations.AlterModelOptions(
            name='exhibittheme',
            options={'verbose_name': 'Exhibit'},
        ),
        migrations.AlterModelOptions(
            name='historicalessayexhibit',
            options={'verbose_name': 'Historical Essay'},
        ),
        migrations.AlterModelOptions(
            name='lessonplanexhibit',
            options={'verbose_name': 'Lesson Plan'},
        ),
        migrations.AlterUniqueTogether(
            name='lessonplantheme',
            unique_together=set([('lessonPlan', 'theme')]),
        ),
        migrations.AlterUniqueTogether(
            name='historicalessaytheme',
            unique_together=set([('historicalEssay', 'theme')]),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalessay',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalessay',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalessay',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='Ready for publication?'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='Ready for publication?'),
        ),
        migrations.AddField(
            model_name='theme',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='theme',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='theme',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='Ready for publication?'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='title',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='historicalessay',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='hero',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Hero Image'),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='theme',
            name='hero',
            field=models.ImageField(blank=True, upload_to='uploads/', verbose_name='Hero Image'),
        ),
        migrations.CreateModel(
            name='BrowseTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkText', models.CharField(max_length=200)),
                ('linkLocation', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='BrowseTermGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', positions.fields.PositionField(default=-1)),
                ('theme', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='exhibits.Theme')),
                ('group_note', models.TextField(blank=True)),
                ('group_title', models.CharField(blank=True, max_length=200)),
                ('render_as', models.CharField(choices=[('H', 'HTML'), ('T', 'Plain Text'), ('M', 'Markdown')], default='H', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='browseterm',
            name='browse_term_group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='exhibits.BrowseTermGroup'),
        ),
        migrations.AddField(
            model_name='browseterm',
            name='order',
            field=positions.fields.PositionField(default=-1),
        ),
        migrations.RenameField(
            model_name='browseterm',
            old_name='linkLocation',
            new_name='link_location',
        ),
        migrations.RenameField(
            model_name='browseterm',
            old_name='linkText',
            new_name='link_text',
        ),
        migrations.AlterModelOptions(
            name='browseterm',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='browsetermgroup',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='exhibit',
            name='scraped_from',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='essay',
        ),
        migrations.AddField(
            model_name='exhibititem',
            name='lesson_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exhibits.LessonPlan'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='byline',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='grade_level',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='lesson_plan',
            field=models.CharField(blank=True, max_length=255, verbose_name='Lesson Plan File URL'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='sub_title',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='exhibititem',
            name='exhibit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exhibits.Exhibit'),
        ),
        migrations.AddField(
            model_name='exhibititem',
            name='lesson_plan_order',
            field=positions.fields.PositionField(default=-1),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='byline_render_as',
            field=models.CharField(choices=[('H', 'HTML'), ('T', 'Plain Text'), ('M', 'Markdown')], default='H', max_length=1),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='short_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterModelOptions(
            name='historicalessayexhibit',
            options={'ordering': ['order'], 'verbose_name': 'Historical Essay'},
        ),
        migrations.AddField(
            model_name='historicalessay',
            name='hero',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Hero Image'),
        ),
        migrations.AddField(
            model_name='historicalessay',
            name='alternate_lockup_derivative',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Alternate Lockup Image'),
        ),
        migrations.AddField(
            model_name='historicalessay',
            name='item_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='historicalessay',
            name='lockup_derivative',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Lockup Image'),
        ),
        migrations.RenameField(
            model_name='historicalessay',
            old_name='about_essay',
            new_name='byline',
        ),
        migrations.AddField(
            model_name='historicalessay',
            name='byline_render_as',
            field=models.CharField(choices=[('H', 'HTML'), ('T', 'Plain Text'), ('M', 'Markdown')], default='H', max_length=1, verbose_name='Render byline as'),
        ),
        migrations.AddField(
            model_name='historicalessay',
            name='go_further_render_as',
            field=models.CharField(choices=[('H', 'HTML'), ('T', 'Plain Text'), ('M', 'Markdown')], default='H', max_length=1, verbose_name='Render as'),
        ),
        migrations.AddField(
            model_name='historicalessay',
            name='color',
            field=models.CharField(blank=True, help_text='Please provide color in <code>#xxx</code>, <code>#xxxxxx</code>, <code>rgb(xxx,xxx,xxx)</code>, or <code>rgba(xxx,xxx,xxx,x.x)</code> formats.', max_length=20),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='alternate_lockup_derivative',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Alternate Lockup Image'),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='item_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='lockup_derivative',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Lockup Image'),
        ),
        migrations.AlterModelOptions(
            name='historicalessaytheme',
            options={'ordering': ['order'], 'verbose_name': 'Historical Essay'},
        ),
        migrations.AlterModelOptions(
            name='lessonplanexhibit',
            options={'ordering': ['order'], 'verbose_name': 'Lesson Plan'},
        ),
        migrations.AlterModelOptions(
            name='lessonplantheme',
            options={'ordering': ['order'], 'verbose_name': 'Lesson Plan'},
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='about_theme',
            new_name='byline',
        ),
        migrations.AddField(
            model_name='theme',
            name='alternate_lockup_derivative',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Alternate Lockup Image'),
        ),
        migrations.AddField(
            model_name='theme',
            name='byline_render_as',
            field=models.CharField(choices=[('H', 'HTML'), ('T', 'Plain Text'), ('M', 'Markdown')], default='H', max_length=1),
        ),
        migrations.AddField(
            model_name='theme',
            name='item_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='theme',
            name='lockup_derivative',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Lockup Image'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='byline_render_as',
            field=models.CharField(choices=[('H', 'HTML'), ('T', 'Plain Text'), ('M', 'Markdown')], default='H', max_length=1),
        ),
        migrations.AddField(
            model_name='exhibititem',
            name='historical_essay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exhibits.HistoricalEssay'),
        ),
        migrations.AddField(
            model_name='exhibititem',
            name='historical_essay_order',
            field=positions.fields.PositionField(default=-1),
        ),
        migrations.AddField(
            model_name='exhibititem',
            name='custom_crop',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/custom_item_crop/'),
        ),
        migrations.AddField(
            model_name='exhibititem',
            name='custom_link',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='lessonplanexhibit',
            name='lessonPlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exhibits.LessonPlan'),
        ),
        migrations.AlterField(
            model_name='lessonplanexhibit',
            name='exhibit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exhibits.Exhibit'),
        ),
        migrations.AlterField(
            model_name='lessonplanexhibit',
            name='exhibit',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='exhibits.Exhibit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessonplanexhibit',
            name='lessonPlan',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='exhibits.LessonPlan'),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='notesitem',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='notesitem',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='browsetermgroup',
            name='exhibit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exhibits.Exhibit'),
        ),
        migrations.AddField(
            model_name='browsetermgroup',
            name='exhibit_order',
            field=positions.fields.PositionField(default=-1),
        ),
        migrations.AlterField(
            model_name='browsetermgroup',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exhibits.Theme'),
        ),
        migrations.AddField(
            model_name='theme',
            name='category',
            field=models.CharField(blank=True, choices=[('cal-history', 'California History'), ('cal-cultures', 'California Cultures'), ('jarda', 'JARDA')], max_length=20),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='hero_first',
            field=models.BooleanField(default=False, verbose_name='Use hero for lockups?'),
        ),
        migrations.AddField(
            model_name='exhibititem',
            name='custom_title',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='historicalessay',
            name='hero_first',
            field=models.BooleanField(default=False, verbose_name='Use hero for lockups?'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hero_first',
            field=models.BooleanField(default=False, verbose_name='Use hero for lockups?'),
        ),
        migrations.AddField(
            model_name='exhibititem',
            name='custom_metadata',
            field=models.TextField(blank=True, verbose_name='Custom metadata'),
        ),
        migrations.AddField(
            model_name='exhibititem',
            name='metadata_render_as',
            field=models.CharField(choices=[('H', 'HTML'), ('T', 'Plain Text'), ('M', 'Markdown')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='item_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='lockup_derivative',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Lockup Image'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sort_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Sortable Title'),
        ),
    ]
