# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import positions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0003_auto_20160301_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEssayExhibit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', positions.fields.PositionField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlanExhibit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', positions.fields.PositionField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='ThemeExhibit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', positions.fields.PositionField(default=-1)),
            ],
        ),
        migrations.AddField(
            model_name='exhibit',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='Ready for publication?'),
        ),
        migrations.AddField(
            model_name='historicalessay',
            name='go_further',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='blockquote',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='essay',
            field=models.TextField(blank=True, verbose_name='Exhibit Overview'),
        ),
        migrations.AlterField(
            model_name='exhibititem',
            name='essay',
            field=models.TextField(blank=True, verbose_name='Item-level exhibit information'),
        ),
        migrations.AlterField(
            model_name='exhibititem',
            name='render_as',
            field=models.CharField(choices=[('H', 'HTML'), ('T', 'Plain Text'), ('M', 'Markdown')], default='T', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalessay',
            name='blockquote',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='essay',
            field=models.TextField(blank=True, verbose_name='Lesson plan'),
        ),
        migrations.AlterField(
            model_name='notesitem',
            name='essay',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='notesitem',
            name='render_as',
            field=models.CharField(choices=[('H', 'HTML'), ('T', 'Plain Text'), ('M', 'Markdown')], default='T', max_length=1),
        ),
        migrations.AddField(
            model_name='themeexhibit',
            name='exhibit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibits.Exhibit'),
        ),
        migrations.AddField(
            model_name='themeexhibit',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibits.Theme'),
        ),
        migrations.AddField(
            model_name='lessonplanexhibit',
            name='exhibit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibits.Exhibit'),
        ),
        migrations.AddField(
            model_name='lessonplanexhibit',
            name='lessonPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibits.LessonPlan'),
        ),
        migrations.AddField(
            model_name='historicalessayexhibit',
            name='exhibit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibits.Exhibit'),
        ),
        migrations.AddField(
            model_name='historicalessayexhibit',
            name='historicalEssay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibits.HistoricalEssay'),
        ),
        migrations.AlterUniqueTogether(
            name='themeexhibit',
            unique_together=set([('exhibit', 'theme')]),
        ),
        migrations.AlterUniqueTogether(
            name='lessonplanexhibit',
            unique_together=set([('exhibit', 'lessonPlan')]),
        ),
        migrations.AlterUniqueTogether(
            name='historicalessayexhibit',
            unique_together=set([('exhibit', 'historicalEssay')]),
        ),
    ]
