# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 23:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0004_auto_20160301_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalessayexhibit',
            old_name='position',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='lessonplanexhibit',
            old_name='position',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='themeexhibit',
            old_name='position',
            new_name='order',
        ),
    ]
