# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0005_auto_20160301_2330'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ThemeExhibit',
            new_name='ExhibitTheme',
        ),
        migrations.AlterField(
            model_name='theme',
            name='essay',
            field=models.TextField(blank=True, verbose_name='Theme overview'),
        ),
    ]
