# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import positions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0006_auto_20160301_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEssayTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', positions.fields.PositionField(default=-1)),
                ('historicalEssay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibits.HistoricalEssay')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibits.Theme')),
            ],
            options={
                'verbose_name': 'Historical Essay',
            },
        ),
        migrations.CreateModel(
            name='LessonPlanTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', positions.fields.PositionField(default=-1)),
                ('lessonPlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibits.LessonPlan')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibits.Theme')),
            ],
            options={
                'verbose_name': 'Lesson Plan',
            },
        ),
        migrations.AlterModelOptions(
            name='exhibittheme',
            options={'verbose_name': 'Exhibit'},
        ),
        migrations.AlterModelOptions(
            name='historicalessayexhibit',
            options={'verbose_name': 'Historical Essay'},
        ),
        migrations.AlterModelOptions(
            name='lessonplanexhibit',
            options={'verbose_name': 'Lesson Plan'},
        ),
        migrations.AlterUniqueTogether(
            name='lessonplantheme',
            unique_together=set([('lessonPlan', 'theme')]),
        ),
        migrations.AlterUniqueTogether(
            name='historicalessaytheme',
            unique_together=set([('historicalEssay', 'theme')]),
        ),
    ]
