# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 22:53
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exhibits', '0007_auto_20160302_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 2, 22, 52, 17, 231128, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exhibit',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exhibit',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 2, 22, 52, 34, 987848, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exhibititem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 2, 22, 52, 42, 602594, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exhibititem',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exhibititem',
            name='exact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exhibititem',
            name='lat',
            field=models.FloatField(default=37.8086906),
        ),
        migrations.AddField(
            model_name='exhibititem',
            name='lon',
            field=models.FloatField(default=-122.2675416),
        ),
        migrations.AddField(
            model_name='exhibititem',
            name='place',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='exhibititem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 2, 22, 52, 52, 147515, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalessay',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 2, 22, 52, 58, 971375, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalessay',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalessay',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalessay',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalessay',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='Ready for publication?'),
        ),
        migrations.AddField(
            model_name='historicalessay',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 2, 22, 53, 15, 647101, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 2, 22, 53, 22, 433910, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='Ready for publication?'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 2, 22, 53, 32, 488220, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notesitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 2, 22, 53, 38, 151063, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notesitem',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notesitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 2, 22, 53, 47, 212055, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 2, 22, 53, 51, 244982, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='theme',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='theme',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='Ready for publication?'),
        ),
        migrations.AddField(
            model_name='theme',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 2, 22, 53, 59, 526772, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='blockquote',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='essay',
            field=models.TextField(verbose_name='Exhibit Overview'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='title',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='historicalessay',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
