# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0008_auto_20160302_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='exhibit',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='exhibit',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='exhibititem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='exhibititem',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='exhibititem',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalessay',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='historicalessay',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='historicalessay',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='notesitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='notesitem',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='notesitem',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='updated_at',
        ),
    ]
