# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0010_exhibit_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='essay',
            field=models.TextField(blank=True, verbose_name='Exhibit Overview'),
        ),
    ]
