# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0011_auto_20160310_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='hero',
            field=models.ImageField(blank=True, upload_to='uploads/', verbose_name='Hero Image'),
        ),
    ]
