# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0013_auto_20160314_2114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BrowseTermGroups',
            new_name='BrowseTermGroup',
        ),
    ]
