# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import positions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0014_auto_20160314_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='browsetermgroup',
            name='browseTerms',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='browseTermGroupsOrder',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='browseTerms',
        ),
        migrations.AddField(
            model_name='browseterm',
            name='browseTermGroup',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='exhibits.BrowseTermGroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='browseterm',
            name='order',
            field=positions.fields.PositionField(default=-1),
        ),
        migrations.AddField(
            model_name='browsetermgroup',
            name='theme',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='exhibits.Theme'),
            preserve_default=False,
        ),
    ]
