# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0015_auto_20160316_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='browseterm',
            old_name='browseTermGroup',
            new_name='browse_term_group',
        ),
        migrations.RenameField(
            model_name='browseterm',
            old_name='linkLocation',
            new_name='link_location',
        ),
        migrations.RenameField(
            model_name='browseterm',
            old_name='linkText',
            new_name='link_text',
        ),
        migrations.RemoveField(
            model_name='browsetermgroup',
            name='groupTitle',
        ),
        migrations.AddField(
            model_name='browsetermgroup',
            name='group_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='browsetermgroup',
            name='group_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='browsetermgroup',
            name='render_as',
            field=models.CharField(choices=[('H', 'HTML'), ('T', 'Plain Text'), ('M', 'Markdown')], default='H', max_length=1),
        ),
    ]
