# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0016_auto_20160316_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='browseterm',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='browsetermgroup',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='exhibit',
            name='scraped_from',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
