# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0017_auto_20160317_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonplan',
            name='essay',
        ),
        migrations.AddField(
            model_name='exhibititem',
            name='lesson_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exhibits.LessonPlan'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='byline',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='grade_level',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='lesson_plan',
            field=models.FileField(blank=True, upload_to='uploads/', verbose_name='Lesson Plan File'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='sub_title',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='exhibititem',
            name='exhibit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exhibits.Exhibit'),
        ),
    ]
