# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0019_exhibititem_lesson_plan_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='byline_render_as',
            field=models.CharField(choices=[('H', 'HTML'), ('T', 'Plain Text'), ('M', 'Markdown')], default='H', max_length=1),
        ),
    ]
