# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0021_auto_20160406_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='short_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
