# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0022_exhibit_short_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageArk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero', models.ImageField(blank=True, upload_to='uploads/', verbose_name='Hero Image')),
                ('lockup_derivative', models.ImageField(blank=True, upload_to='uploads/', verbose_name='Lockup Image')),
                ('alternate_lockup_derivative', models.ImageField(blank=True, upload_to='uploads/', verbose_name='Alternate Lockup Image')),
                ('item_id', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='historicalessayexhibit',
            options={'ordering': ['order'], 'verbose_name': 'Historical Essay'},
        ),
        migrations.AddField(
            model_name='historicalessay',
            name='hero',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exhibits.ImageArk'),
        ),
    ]
