# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0023_auto_20160406_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalessay',
            name='alternate_lockup_derivative',
            field=models.ImageField(blank=True, upload_to='uploads/', verbose_name='Alternate Lockup Image'),
        ),
        migrations.AddField(
            model_name='historicalessay',
            name='item_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='historicalessay',
            name='lockup_derivative',
            field=models.ImageField(blank=True, upload_to='uploads/', verbose_name='Lockup Image'),
        ),
        migrations.AlterField(
            model_name='historicalessay',
            name='hero',
            field=models.ImageField(blank=True, upload_to='uploads/', verbose_name='Hero Image'),
        ),
        migrations.DeleteModel(
            name='ImageArk',
        ),
    ]
