# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0025_auto_20160406_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalessay',
            old_name='about_essay',
            new_name='byline',
        ),
        migrations.AddField(
            model_name='historicalessay',
            name='byline_render_as',
            field=models.CharField(choices=[('H', 'HTML'), ('T', 'Plain Text'), ('M', 'Markdown')], default='H', max_length=1),
        ),
        migrations.AddField(
            model_name='historicalessay',
            name='go_further_render_as',
            field=models.CharField(choices=[('H', 'HTML'), ('T', 'Plain Text'), ('M', 'Markdown')], default='H', max_length=1),
        ),
    ]
