# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0026_auto_20160406_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalessay',
            name='color',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
