# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0027_historicalessay_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='alternate_lockup_derivative',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Alternate Lockup Image'),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='item_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='lockup_derivative',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Lockup Image'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='hero',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Hero Image'),
        ),
    ]
