# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0028_auto_20160406_2109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalessaytheme',
            options={'ordering': ['order'], 'verbose_name': 'Historical Essay'},
        ),
        migrations.AlterModelOptions(
            name='lessonplanexhibit',
            options={'ordering': ['order'], 'verbose_name': 'Lesson Plan'},
        ),
        migrations.AlterModelOptions(
            name='lessonplantheme',
            options={'ordering': ['order'], 'verbose_name': 'Lesson Plan'},
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='about_theme',
            new_name='byline',
        ),
        migrations.AddField(
            model_name='theme',
            name='alternate_lockup_derivative',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Alternate Lockup Image'),
        ),
        migrations.AddField(
            model_name='theme',
            name='byline_render_as',
            field=models.CharField(choices=[('H', 'HTML'), ('T', 'Plain Text'), ('M', 'Markdown')], default='H', max_length=1),
        ),
        migrations.AddField(
            model_name='theme',
            name='item_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='theme',
            name='lockup_derivative',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Lockup Image'),
        ),
    ]
