# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import positions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0030_lessonplan_byline_render_as'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibititem',
            name='historical_essay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exhibits.HistoricalEssay'),
        ),
        migrations.AddField(
            model_name='exhibititem',
            name='historical_essay_order',
            field=positions.fields.PositionField(default=-1),
        ),
    ]
