# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 17:05
from __future__ import unicode_literals

from django.db import migrations
import exhibits.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0032_auto_20160407_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='hero',
            field=exhibits.custom_fields.HeroField(blank=True, null=True, upload_to='uploads/', verbose_name='Hero Image'),
        ),
    ]
