# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-25 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0033_auto_20160421_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplanexhibit',
            name='lessonPlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exhibits.LessonPlan'),
        ),
    ]
