# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-25 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0035_auto_20160425_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplanexhibit',
            name='exhibit',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='exhibits.Exhibit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessonplanexhibit',
            name='lessonPlan',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='exhibits.LessonPlan'),
            preserve_default=False,
        ),
    ]
