# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-09 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0037_auto_20160505_0037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notesitem',
            options={'ordering': ['order']},
        ),
    ]
