# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-09 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0038_auto_20160509_1930'),
        ('exhibits', '0038_auto_20160509_1923'),
    ]

    operations = [
    ]
