# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-17 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0039_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='category',
            field=models.CharField(blank=True, choices=[('calhistory', 'California History'), ('calcultures', 'California Cultures'), ('jarda', 'California')], max_length=20),
        ),
    ]
