# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-17 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0040_theme_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='category',
            field=models.CharField(blank=True, choices=[('cal-history', 'California History'), ('cal-cultures', 'California Cultures'), ('jarda', 'JARDA')], max_length=20),
        ),
    ]
