# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-20 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0041_auto_20160517_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='hero_first',
            field=models.BooleanField(default=False, verbose_name='Use hero for lockups?'),
        ),
        migrations.AddField(
            model_name='exhibititem',
            name='custom_title',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='historicalessay',
            name='hero_first',
            field=models.BooleanField(default=False, verbose_name='Use hero for lockups?'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hero_first',
            field=models.BooleanField(default=False, verbose_name='Use hero for lockups?'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='lesson_plan',
            field=models.CharField(max_length=255, verbose_name='Lesson Plan File URL'),
        ),
    ]
